# Generated by Makr 1.0.4
# https://github.com/willowtreeapps/Makr

# Path for built products
ARTIFACTS_PATH = artifacts

# Path for built archives
ARCHIVES_PATH = $(ARTIFACTS_PATH)/archives

# Path for built IPAs
IPAS_PATH = $(ARTIFACTS_PATH)/ipas

# Provisioning profiles dir
PROFILES_DIR = $(CURDIR)/profiles

# Temporary build dir
TEMP_DIR = $(CURDIR)/tmp

# Build environment vars
CONFIGURATION_BUILD_DIR = $(TEMP_DIR)/configuration

BUILD_ENV_OPTIONS = SHARED_PRECOMPS_DIR="$(TEMP_DIR)/precomps" \
		TARGET_TEMP_DIR="$(TEMP_DIR)/target/" \

# Archives
ARCHIVES = $(ARCHIVES_PATH)/EXPERTconnect-App.xcarchive 

# IPAs
IPAS = $(IPAS_PATH)/EXPERTconnectDemo.ipa 
# Generates all IPAs
all: $(IPAS)

# Create profiles directory
$(PROFILES_DIR):
	mkdir $@

# Install provisioning profiles
install-profiles: $(PROFILES_DIR)
	rsync -av ./profiles/ ~/Library/MobileDevice/Provisioning\ Profiles/

# Create EXPERTconnect-App.xcarchive
$(ARCHIVES_PATH)/EXPERTconnect-App.xcarchive:
	xcodebuild archive $(BUILD_ENV_OPTIONS) \
		-scheme "EXPERTconnectDemo" \
		-workspace "EXPERTconnect.xcworkspace" \
						-configuration "Release"  \
		-archivePath $@
	rm -rf $(TEMP_DIR)

# Create EXPERTconnectDemo.ipa
$(IPAS_PATH)/EXPERTconnectDemo.ipa: $(IPAS_PATH) $(ARCHIVES_PATH)/EXPERTconnect-App.xcarchive
	xcodebuild -exportArchive \
		-exportFormat IPA \
		-exportProvisioningProfile "HumanifyExpertConnectDemo" \
		-archivePath "$(ARCHIVES_PATH)/EXPERTconnect-App.xcarchive" \
		-exportPath "$@"

# Upload EXPERTconnectDemo.ipa to hockeyapp
distribute-EXPERTconnectDemo-Humanify EXPERTconnect - iOS Internal:
	curl https://rink.hockeyapp.net/api/2/apps/upload \
	-H 'X-HockeyAppToken: $(HOCKEY_APP_ID)' \
	-F ipa=@'$(IPAS_PATH)/EXPERTconnectDemo.ipa' \
	-F notes='New build!' \
	-F notes_type='0' \
	-F notify='0' \
	-F status='2' \
	-F tags='' \
	-F teams='' \
	-F users='' \
	-F mandatory='0' \
	-F release_type='0' \
	-F private='false' \
	-F commit_sha='' \
	-F build_server_url='' \
	-F repository_url='' \

# Path to built IPAs
$(IPAS_PATH):
	mkdir -p $(IPAS_PATH)

# Run all distribution tasks
distribute-all:  distribute-EXPERTconnectDemo-Humanify EXPERTconnect - iOS Internal


# Clean artifacts and temp directories
clean:
	rm -rf $(ARTIFACTS_PATH)
	rm -rf $(TEMP_DIR)
